"""
ai_repo_sentinel.py
Autonomous Quantitative Repo Auditor & Chief Risk Officer (CRO) Engine.
Powered by OpenRouter Free Tier Neural Models.

Capabilities:
- Comprehensive File Integrity & Syntax Auditor (Zero Line-454 Reoccurrence)
- GEX/DEX Boundary Arbitrage & Anomaly Scanner
- Macro Correlation Verification (US10Y Yields, COT, News Gate)
- Execution Performance & Risk-Reward Audit (from scalp_log.csv)
- Automated Telegram Decision Dispatch & Actionable Strategy Recommendations
"""

import os
import glob
import json
import ast
import requests
import pandas as pd
from datetime import datetime, timezone

# ================= CREDENTIALS & SECRETS =================
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip()
TELEGRAM_BOT_TOKEN = (
    os.getenv("TELEGRAM_BOT_TOKEN", "") 
    or os.getenv("BOT_TOKEN", "")
).strip()
TELEGRAM_CHAT_ID = (
    os.getenv("TELEGRAM_CHAT_ID", "") 
    or os.getenv("CHAT_ID", "")
).strip()

OPENROUTER_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"
# Using high-capacity free reasoning & analysis models on OpenRouter
MODEL_CANDIDATES = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "google/gemini-2.0-flash-exp:free",
    "deepseek/deepseek-r1:free",
    "qwen/qwen-2.5-72b-instruct:free"
]

def dispatch_telegram(html_text: str) -> bool:
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        print("[SENTINEL TG] Credentials missing.")
        return False
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        res = requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": html_text, "parse_mode": "HTML"}, timeout=10)
        return res.status_code == 200
    except Exception as e:
        print(f"[SENTINEL TG ERROR] {e}")
        return False

# ================= 1. CODEBASE SYNTAX & INTEGRITY AUDITOR =================
def audit_python_files() -> dict:
    """Parses Python ASTs across the repo to catch truncation or syntax defects before GitHub Actions runs."""
    audit_results = {}
    py_files = glob.glob("*.py")
    
    for fpath in py_files:
        try:
            with open(fpath, "r", encoding="utf-8") as f:
                source = f.read()
            ast.parse(source)
            audit_results[fpath] = "VALID_AST"
        except SyntaxError as se:
            audit_results[fpath] = f"SYNTAX_ERROR: Line {se.lineno} - {se.msg}"
        except Exception as e:
            audit_results[fpath] = f"READ_ERROR: {e}"
            
    return audit_results

# ================= 2. TELEMETRY & QUANT STATE INGESTION =================
def ingest_quant_state() -> dict:
    """Aggregates all JSON and CSV telemetry caches generated by the engines."""
    state = {
        "gex": {},
        "macro": {},
        "cot": {},
        "recent_trades": [],
        "news_shocks": []
    }
    
    # 1. GEX Levels
    if os.path.exists("gex_levels.json"):
        try:
            with open("gex_levels.json", "r") as f:
                state["gex"] = json.load(f)
        except Exception:
            pass

    # 2. Macro Yields
    if os.path.exists("lse_macro.csv"):
        try:
            df_m = pd.read_csv("lse_macro.csv")
            if not df_m.empty:
                state["macro"] = df_m.iloc[-1].to_dict()
        except Exception:
            pass

    # 3. COT Positioning
    if os.path.exists("cot_positioning.json"):
        try:
            with open("cot_positioning.json", "r") as f:
                state["cot"] = json.load(f)
        except Exception:
            pass

    # 4. Scalp Execution Logs
    if os.path.exists("scalp_log.csv"):
        try:
            df_s = pd.read_csv("scalp_log.csv")
            if not df_s.empty:
                state["recent_trades"] = df_s.tail(5).to_dict(orient="records")
        except Exception:
            pass

    # 5. News Sentiment History
    if os.path.exists("news_sentiment_history.csv"):
        try:
            df_n = pd.read_csv("news_sentiment_history.csv")
            if not df_n.empty:
                state["news_shocks"] = df_n.tail(3).to_dict(orient="records")
        except Exception:
            pass

    return state

# ================= 3. OPENROUTER AI REASONING KERNEL =================
def query_openrouter_audit(code_status: dict, quant_state: dict) -> str:
    """Prompts OpenRouter Free Models to act as an Institutional Quantitative Risk Officer."""
    if not OPENROUTER_API_KEY:
        return "⚠️ OPENROUTER_API_KEY is not defined. Cannot generate neural audit."

    prompt = f"""
You are the Chief Risk Officer (CRO) and Lead Quantitative Strategist for an institutional Gold (XAU/USD) systematic fund.
Analyze the following telemetry snapshot and repository code health:

### 1. REPO CODE INTEGRITY AUDIT:
{json.dumps(code_status, indent=2)}

### 2. QUANT TELEMETRY & MARKET REGIME:
- GEX Levels & Dealer Exposure: {json.dumps(quant_state.get('gex'), indent=2)}
- Macro Yields & Shield: {json.dumps(quant_state.get('macro'), indent=2)}
- COT Institutional Positioning: {json.dumps(quant_state.get('cot'), indent=2)}
- Recent Executions: {json.dumps(quant_state.get('recent_trades'), indent=2)}
- Recent Macro Surprise Prints: {json.dumps(quant_state.get('news_shocks'), indent=2)}

### REQUIRED OUTPUT (Be concise, direct, and institutional. No generic fluff):
1. **System Health Verdict**: (PASSED / CRITICAL / WARN)
2. **Current Market Regime Analysis**: (Gamma regime, US10Y bond direction, COT bias, and whether walls are safe or under squeeze risk)
3. **Execution & Risk Assessment**: (Evaluation of recent trades or risk-reward alignment)
4. **Actionable Suggestions / Autonomous Decision**: (Clear directive: e.g. Maintain trading, Widen stops, Block long scalp, or Adjust flip baseline)

Provide your response in clean HTML format using only <b>, <code>, and list tags for easy scannability in Telegram. Keep total length under 300 words.
"""

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/parfactmatch-cloud/gold-macro-dashboard",
        "X-Title": "Gold Quant Risk Sentinel"
    }

    for model in MODEL_CANDIDATES:
        try:
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are a quantitative hedge fund risk auditor."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.2,
                "max_tokens": 700
            }
            res = requests.post(OPENROUTER_ENDPOINT, headers=headers, json=payload, timeout=25)
            if res.status_code == 200:
                result = res.json()
                return result["choices"][0]["message"]["content"].strip()
            else:
                print(f"[MODEL SKIP] {model} returned HTTP {res.status_code}: {res.text[:100]}")
        except Exception as e:
            print(f"[MODEL ERROR] {model} failed: {e}")

    return "❌ All OpenRouter free candidate models timed out or failed to respond."

# ================= 4. MAIN AUDIT WORKER =================
def run_full_repo_audit():
    now_utc = datetime.now(timezone.utc).strftime("%H:%M UTC | %d %b %Y")
    print(f"[SENTINEL RUN] Initiating Autonomous Repo Audit at {now_utc}...")

    # Step 1: Code Syntax Audit
    code_status = audit_python_files()
    has_syntax_flaw = any("SYNTAX_ERROR" in str(v) for v in code_status.values())

    # Step 2: Telemetry Ingestion
    quant_state = ingest_quant_state()

    # Step 3: Neural AI Audit Reasoning
    ai_verdict = query_openrouter_audit(code_status, quant_state)

    # Step 4: Dispatch Telegram Audit Card
    tg_card = (
        f"🤖 <b>QUANT AI REPO SENTINEL & CRO AUDIT</b>\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"⏰ <b>Audit Epoch</b>: <code>{now_utc}</code>\n"
        f"🛡️ <b>Codebase Integrity</b>: {'🔴 SYNTAX DEFECT DETECTED' if has_syntax_flaw else '🟢 100% AST PARSED'}\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"{ai_verdict}\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"⚡ <i>Autonomous Institutional Risk Assessment</i>"
    )

    dispatch_telegram(tg_card)
    print("[SENTINEL COMPLETE] CRO Audit dispatched to Telegram.")

if __name__ == "__main__":
    run_full_repo_audit()

